### ISSUE TITLE
Allow `no-unused-expressions` rule

### ISSUE THREAD

**Issue by ricardogama** [seegno/eslint-config-seegno#7] opened 2015-11-05 16:58 UTC
This code is often used, at least on the controllers tests asserts:

```js
...
.expect((res) => {
  res.body.should.be.an.Object;
  ...
```

But this rule does not allow it:

```
error  Unexpected parentheses around single function argument     arrow-parens
```

How about disabling it?

**Comment by ruiquelhas** [comment] 2015-11-05 17:28
Duplicate of #6.

**Closed by ruiquelhas** 2015-11-05 17:28 UTC
Labels: duplicate
